### ISSUE TITLE
How to set the delay time

### ISSUE THREAD

**Issue by ewecan** [DuyTrandeLion/peripheral-drivers#1]
Hello, if on a 32Mhz microcontroller, how should I set the delay function？

`		.delayHandle = NULL`

**Comment by DuyTrandeLion** [comment]
You can see the example here: https://github.com/DuyTrandeLion/peripheral-drivers/blob/master/AD9833/example/stm32f767zi_ad9833/Core/Src/main.c

As `delayHandle` is a function pointer, it is your choice to handle how the delay works regardless the MCU frequency.
